language: ruby
rvm:
- 2.0.0
deploy:
  - provider: heroku
    api_key:
      secure: NWYu0M7rvxm7PbYIdhH3yH2k145jeG5O76igHejwJwmEisdmZb8w7xcuSMswkNOdcDNHAPpcYSS264Wse1veM6uvadH3337E98FiWoQgCSRs/rLT2g2dqAK1n1R0f+RBYgn5xf0frDevVYaq7NwIa7MR6T1lGdFVAcwhzxxRTXE=
    app: dius-project-health
    on:
      repo: DiUS/project-health